//
// Generated file, do not edit! Created by nedtool 4.6 from CoreNode/ControlUnitInfo.msg.
//

#ifndef _CONTROLUNITINFO_M_H_
#define _CONTROLUNITINFO_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>CoreNode/ControlUnitInfo.msg:25</tt> by nedtool.
 * <pre>
 * //
 * // Auto-mensaje usado en CoreControlUnit para programar las conexiones y desconexiones del módulo OXC.
 * //
 * // Este tipo de mensaje puede tomar dos valores:
 * //
 * // - OBS_SCHEDULE_OXC (1)
 * // - OBS_UNSCHEDULE_OXC (2): En este caso, solo será leído el campo inGate.
 * //
 * message OBS_ControlUnitInfo
 * {
 *     int inGate = -1; // compuerta de entrada OXC 
 *     int outGate = -1; //compuerta de salida OXC 
 * }
 * </pre>
 */
class OBS_ControlUnitInfo : public ::cMessage
{
  protected:
    int inGate_var;
    int outGate_var;

  private:
    void copy(const OBS_ControlUnitInfo& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const OBS_ControlUnitInfo&);

  public:
    OBS_ControlUnitInfo(const char *name=NULL, int kind=0);
    OBS_ControlUnitInfo(const OBS_ControlUnitInfo& other);
    virtual ~OBS_ControlUnitInfo();
    OBS_ControlUnitInfo& operator=(const OBS_ControlUnitInfo& other);
    virtual OBS_ControlUnitInfo *dup() const {return new OBS_ControlUnitInfo(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getInGate() const;
    virtual void setInGate(int inGate);
    virtual int getOutGate() const;
    virtual void setOutGate(int outGate);
};

inline void doPacking(cCommBuffer *b, OBS_ControlUnitInfo& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, OBS_ControlUnitInfo& obj) {obj.parsimUnpack(b);}


#endif // ifndef _CONTROLUNITINFO_M_H_

