//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public License
// along with this program.  If not, see http://www.gnu.org/licenses/.
//
//
//
//clase mensajes que almacena temporalmente la informacion actualizada del BCP correspondiente a su longitud de onda de salida, destino, y compuerta de salida
//esta informacion es transmitida al BCP para que éste pueda seguir con su camino
//actua en la clase CoreRouting
//
//
//

class CoreRouting
{
    int outPort = -1;
    int outLabel = -1;
    int outColor = -1;

}